---
title: "DrainDown trend"
author: "Farshad Ebrahimi"
date: "2025-08-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# estimate discharge
#pool for database connections
library(pool)
#odbc for database connections
library(odbc)
#DBI
library(DBI)
#tidyverse for data manipulations
library(tidyverse)
#lubridate to work with dates
library(lubridate)
# smoothing library
library(forecast)

# DB connections & functions
poolConn <- dbPool(RPostgres::Postgres(),
                   host = "PWDMARSDBS1.pwd.phila.local",
                   port = 5434,
                   dbname = "mars_prod",
                   user = Sys.getenv("admin_uid"),
                   password = Sys.getenv("admin_pwd"),
                   timezone = NULL)
```

```{r targeted smp and design metrics}

smp_id <- "366-2-2" #trench with ~9 years of cwl data
system_id <- "366-2" 

design_metrics <- dbGetQuery(poolConn, paste("SELECT * FROM external.tbl_systembdv where system_id ='", system_id, "'", sep = ""))

sump_depth_ft <- 1.2
# no underdrain and no orrifice
storage_depth_ft <- 5.92

# stormsized managed = 2in
storm_size_managed <- 2

rain_data <- dbGetQuery(poolConn, "Select * from data.tbl_gage_event where gage_uid = 9 AND eventdatastart > '2013-10-30'")

cwl_data <- dbGetQuery(poolConn, "Select * from data.viw_ow_leveldata_sumpcorrected where ow_suffix = 'OW1' AND smp_id = '366-2-2'")
```

```{r filter rain events of 2, echo=FALSE}

# check to see i rain occured within 72 hours of each storm

rain_test <- rain_data %>%
  mutate(rain_within_threedays = "No") %>%
  mutate(start_level = NA) %>%
  mutate(max_level = NA) %>%
  mutate(max_level_timestamp = as.POSIXct(NA)) %>%
  mutate(level_at_seventytwo = NA) %>%
  mutate(drain_timestamp = as.POSIXct(NA))



for (i in 1: (nrow(rain_test)-1)) {
  if(rain_test[i+1, ]$eventdatastart < rain_test[i, ]$eventdatastart + days(3)) {
    rain_test[i,"rain_within_threedays"] <- "Yes"
  }
}

rain_data_designed <- rain_test %>%
  filter(rain_within_threedays == "No")

```

```{r get starting level min max from the water level timeseries for the 72 hour span from start of rain }

for (j in 1:nrow(rain_data_designed)) {
  temp_level <- cwl_data %>%
    filter(dtime > rain_data_designed$eventdatastart[j] & dtime < rain_data_designed$eventdataend[j])
  
  temp_level_at72 <- cwl_data %>%
    filter(dtime > rain_data_designed$eventdatastart[j] & dtime < rain_data_designed$eventdatastart[j] + days(3))
  
  rain_data_designed[j,"start_level"] <- temp_level$level_ft[1]
  rain_data_designed[j,"max_level"] <- max(temp_level$level_ft)
  rain_data_designed[j,"max_level_timestamp"] <- temp_level %>%
    filter(level_ft == max(temp_level$level_ft)) %>%
    select(dtime) %>%
    pull() %>%
    .[1]
  rain_data_designed[j,"level_at_seventytwo"] <- temp_level_at72$level_ft[length(temp_level_at72)]
  
  rain_data_designed[j,"drain_timestamp"] <- temp_level_at72 %>%
    filter(dtime > rain_data_designed[j, "max_level_timestamp"]  & level_ft == 0) %>%
    select(dtime) %>%
    pull() %>%
    .[1]

}

# look at response 0.5 foot and higher
summary_half_foot <- rain_data_designed %>%
  filter(max_level > 0.5) %>%
  mutate(draindown_duration = drain_timestamp - max_level_timestamp) %>%
  mutate(draindown_duration_raindepth_normed = draindown_duration/eventdepth_in) %>%
  mutate(draindown_duration_intensity_normed = draindown_duration/eventpeakintensity_inhr)


```

